Close mobile navigation on resize to desktop site
4teamwork/ftw.mobile pull request #45
Opened 2016-11-14 13:59 UTC by raphael-s

Fixes an edge case where the site is resized to desktop sized while the mobile navigation is open. This would lead to the page removing the mobile navigation but not sliding the page back in:
<img width="1440" alt="screen shot 2016-11-14 at 14 56 51" src="https://cloud.githubusercontent.com/assets/16755391/20267379/bb404cd2-aa7a-11e6-82c3-30af78d84e00.png">

This is now checked on every resize of the page and if the mobile navigation suddenly disappears it will slide the content back in.

2016-11-17 12:53 UTC, bierik requested changes
I suggest to toggle the mobile navigation using CSS. The initial state of the offcanvas content when `menu-open` is on the root would be `transition: translate...`. When the screen reaches the medium viewport the transition would be set to `none`

``` scss
@include transform(...);
@inlcude screen-medium() {
 @include transform(none);
}
```

2016-11-21 14:05 UTC, raphael-s commented
@bierik this is now done by using `scss` as you suggested. Looks like it does the same thing to me, can you review this again? Thanks 😃

2016-11-23 17:05 UTC, bierik approved these changes

2016-11-25 09:21 UTC, maethu commented
wow, nice, simple, clean solution. I was not aware of the this simple css solution. 

@bierik  💖

2016-11-25 09:34 UTC, merged