Make compatible with ftw.theming 2.0.0
4teamwork/ftw.mobile pull request #53
Opened 2017-07-17 09:15 UTC by bierik

2017-07-17 09:27 UTC, mbaechtold requested changes
Please update the required version in https://github.com/4teamwork/ftw.mobile/blob/master/setup.py#L61

2017-07-19 16:53 UTC, bierik commented
@mbaechtold updated

2017-07-20 06:46 UTC, mbaechtold requested changes

2017-07-20 06:46 UTC, mbaechtold commented on setup.py
> +          'ftw.theming >= 2.0.0',
This has not been released yet?!?

2017-07-20 06:49 UTC, bierik commented on setup.py
> +          'ftw.theming >= 2.0.0',
I know thats why it requires https://github.com/4teamwork/ftw.theming/pull/85 😄

2018-01-17 08:16 UTC, bierik commented
@mbaechtold ftw.theming 2.0.0 is released and test are passing

2018-01-17 08:18 UTC, mbaechtold approved these changes

2018-01-17 08:19 UTC, merged